version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ng serve --host 0.0.0.0 --poll=2000 --disable-host-check
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4200/"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s 